use_x509userproxy = true
universe = vanilla
Executable = /uscms_data/d3/kjohnso/BtoTW/CMSSW_11_0_0/src/vlq-BtoTW-RDF/condorRDF.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
Transfer_Input_Files = /uscms/home/kjohnso/nobackup/rdfjobs.tar
Output = singleTb_RDF_0.out
Error = singleTb_RDF_0.err
Log = singleTb_RDF_0.log
Notification = Never
Arguments = condor/singleTb.txt /store/user/kjohnso/vlq-BtoTW-RDF/singleTb 0 




Queue 1